# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.6"
  #- "3.5-dev" # 3.5 development branch
  #- "nightly" # points to the latest development branch e.g. 3.6-dev
before_install:
  - sudo apt-get install mediainfo
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
